// All player-visible text. Switching language = swapping this data, no code changes.
export const STR = {
  title: "КРЫСИНАЯ ОРДА",
  subtitle: "Top-down rogue-like шутер",
  start: "ИГРАТЬ",
  howToTitle: "Управление",
  howKbd: "WASD / стрелки — движение · мышь — прицел · ЛКМ / пробел — огонь",
  howPad: "Геймпад: левый стик — ход, правый стик — прицел и огонь",
  howTouch: "Тач: левая половина — ход, правая — прицел и огонь",
  hpLabel: "HP",
  waveLabel: "ВОЛНА",
  scoreLabel: "ОЧКИ",
  killsLabel: "КРЫСЫ",
  waveCleared: "ВОЛНА ЗАЧИЩЕНА",
  chooseUpgrade: "ВЫБЕРИ УЛУЧШЕНИЕ",
  pickHint: "клик / 1·2·3 / геймпад",
  gameOver: "ТЕБЯ ЗАГРЫЗЛИ",
  finalScore: "Итог",
  finalWave: "Дошёл до волны",
  restart: "ЗАНОВО",
  paused: "ПАУЗА",
  upgrades: {
    damage:    { name: "Калибр+",      desc: "Урон пули +1" },
    firerate:  { name: "Скорострел",   desc: "Темп стрельбы +18%" },
    speed:     { name: "Беговые лапы",  desc: "Скорость хода +12%" },
    multishot: { name: "Веер",         desc: "+1 пуля за выстрел" },
    pierce:    { name: "Бронебой",     desc: "Пуля пробивает +1 цель" },
    health:    { name: "Аптечка",      desc: "Макс. HP +25 и лечение" },
    bulletspd: { name: "Разгон",       desc: "Скорость пули +25%" },
    lifesteal: { name: "Вампиризм",    desc: "+2 HP за убийство" },
  },
};
